---

- hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Install EFS utils
      yum:
        name: amazon-efs-utils
        state: latest
    - name: Create mount folder
      file:
        path: /mnt/efs
        state: directory
    - name: Mount EFS
      mount:
        path: /mnt/efs
        src: fs-0b15342a59a4e9b98
        fstype: efs
        opts: tls
        state: mounted
