---

- hosts: localhost
  connection: local
  become: true
  vars:
    mount_folder: "/mnt/efs"
  tasks:
    - name: Install EFS utils
      yum:
        name: amazon-efs-utils
        state: latest
    - name: Create mount folder
      file:
        path: "{{ mount_folder }}"
        state: directory
    - name: Mount EFS
      mount:
        path: "{{ mount_folder }}"
        src: "{{ lookup('env', 'EFS_ID') }}"
        fstype: efs
        opts: tls
        state: mounted
