---

- hosts: localhost
  connection: local
  become: true
  roles:
    - role: base
      tags:
        - always
    - role: docker
      tags:
        - docker
    - role: mount_efs
      tags:
        - mount_efs
    - role: nginx
      tags:
        - nginx