---

- hosts: localhost
  connection: local
  become: true
  vars:
    mount_folder: "/mnt/efs"
    efs_utils_folder: "/home/ubuntu/efs-utils/"
  tasks:
    - include_tasks: tasks/install_efs_utils_{{ ansible_distribution | lower }}.yaml
    - name: Create mount folder
      file:
        path: "{{ mount_folder }}"
        state: directory
    - name: Mount EFS
      mount:
        path: "{{ mount_folder }}"
        src: "{{ lookup('env', 'EFS_ID') }}"
        fstype: efs
        opts: tls
        state: mounted
