---

- name: Install required packages
  block:
    - name: Install prerequisite packages
      yum:
        name:
          - yum-utils
    - name: Add Terraform repo
      yum_repository:
        name: hashicorp
        baseurl: https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
        enabled: yes
        gpgcheck: yes
        gpgkey: https://rpm.releases.hashicorp.com/gpg
    - name: Install terraform
      yum:
        name:
          - terraform
        update_cache: true