---

- name: Install required packages
  block:
    - name: Install prerequisite packages
      yum:
        name:
          - yum-utils
    - name: Add Terraform repo
      shell: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
    - name: Install terraform
      yum:
        name:
          - terraform
        update_cache: true
    - name: Install ngrok
      unarchive:
        src: https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        dest: /usr/local/bin
        remote_src: yes