---

- name: Install EFS utils (Ubuntu)
  block:
    - name: Install binutils
      apt:
        name: binutils
        state: latest
    - name: Clone efs-utils repo
      git:
        repo: https://github.com/aws/efs-utils
        dest: "{{ efs_utils_folder }}"
        clone: yes
        update: yes
    - name: Run build-deb.sh script
      shell: ./build-deb.sh
      args:
        chdir: "{{ efs_utils_folder }}"
        creates: build/amazon-efs-utils*deb
    - name: Install efs-utils package
      shell: apt -y install ./build/amazon-efs-utils*deb
      args:
        chdir: "{{ efs_utils_folder }}"
      register: efs_utils_pkg_install
      changed_when: '"Unpacking amazon-efs-utils" in efs_utils_pkg_install.stdout'