---

- include_tasks: ./install_{{ ansible_distribution | lower }}.yml
- name: Start Docker service
  service:
    name: docker
    state: started
- name: Add user to docker group
  user:
    name: "{{ lookup('env', 'USER') }}"
    groups: docker
    append: yes